#!/usr/bin/env python3
"""Smoke test for the in-process Pipecat TTSService.

Runs a minimal pipeline (MegakernelTTSService -> collector), pushes a
TTSSpeakFrame, and checks that PCM frames stream out incrementally. Reports
time-to-first-audio-frame and writes the result to /tmp/pipecat_tts_test.wav.

    python3 tests/test_pipecat_tts.py
"""

import asyncio
import os
import sys
import time
import wave

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pipecat.frames.frames import EndFrame, Frame, TTSAudioRawFrame, TTSSpeakFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor

TEXT = "Hello! This audio was generated by the megakernel inside a Pipecat pipeline."
OUT_WAV = "/tmp/pipecat_tts_test.wav"


class AudioCollector(FrameProcessor):
    def __init__(self):
        super().__init__()
        self.chunk_times: list[float] = []
        self.pcm = bytearray()
        self.sample_rate = 24000

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)
        if isinstance(frame, TTSAudioRawFrame):
            self.chunk_times.append(time.perf_counter())
            self.pcm.extend(frame.audio)
            self.sample_rate = frame.sample_rate
        await self.push_frame(frame, direction)


async def main():
    from qwen_tts_megakernel.engine import MegakernelTTS
    from qwen_tts_megakernel.pipecat_tts import MegakernelTTSService

    gen_params = {}
    if len(sys.argv) > 1:
        gen_params["first_chunk_frames"] = int(sys.argv[1])

    print("Loading engine (model + CUDA graphs)...")
    engine = MegakernelTTS()
    # Warm with the same chunking so the first real utterance doesn't pay
    # cold-start costs for the codec decode shapes.
    for _ in engine.stream("Warm up.", speaker="ryan", max_new_tokens=30, **gen_params):
        pass
    tts = MegakernelTTSService(engine=engine, speaker="ryan", gen_params=gen_params)
    collector = AudioCollector()
    pipeline = Pipeline([tts, collector])
    task = PipelineTask(pipeline, params=PipelineParams(enable_metrics=True))

    t0 = time.perf_counter()
    await task.queue_frames([TTSSpeakFrame(TEXT), TTSSpeakFrame(TEXT), EndFrame()])
    await PipelineRunner(handle_sigint=False).run(task)

    assert collector.pcm, "no audio frames received"
    n_chunks = len(collector.chunk_times)
    assert n_chunks > 1, f"expected incremental streaming, got {n_chunks} chunk(s)"

    ttfb = collector.chunk_times[0] - t0
    dur = len(collector.pcm) / 2 / collector.sample_rate
    with wave.open(OUT_WAV, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(collector.sample_rate)
        w.writeframes(bytes(collector.pcm))

    print(f"OK: {n_chunks} streamed chunks, first frame after {ttfb*1000:.0f} ms, "
          f"{dur:.1f}s audio @ {collector.sample_rate} Hz -> {OUT_WAV}")


if __name__ == "__main__":
    asyncio.run(main())
